<?php

/**
 * @file
 * Contains openkj.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function openkj_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the openkj module.
    case 'help.page.openkj':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OpenKJ Integration') . '</p>';
      return $output;

    default:
  }
}
