services:

  # What to call the service hosting the site.
  php:

    # Use PHP 7.2 with Apache
    image: tugboatqa/php:7.2-apache

    # Set this as the default service. This does a few things
    #   1. Clones the git repository into the service container
    #   2. Exposes port 80 to the Tugboat HTTP proxy
    #   3. Routes requests to the preview URL to this service
    default: true

    # Wait until the mysql service is done building
    depends: mysql

    # A set of commands to run while building this service
    commands:

      # Commands that set up the basic preview infrastructure
      init:

        # Install prerequisite packages
        - apt-get update
        - apt-get install -y mysql-client

        # Install drush-launcher
        - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
        - chmod +x /usr/local/bin/drush
        - composer global require hirak/prestissimo
        - composer create-project drupal-composer/drupal-project:8.x-dev ~/test-drupal --stability dev --no-interaction
        - composer require -d ~/test-drupal wikimedia/composer-merge-plugin
        - mkdir -p ~/test-drupal/web/modules/custom
        - mkdir -p ~/test-drupal/web/sites/default/
        - ln -s "${TUGBOAT_ROOT}" ~/test-drupal/web/modules/custom/openkj
        - composer config -d ~/test-drupal extra.merge-plugin.require "web/modules/custom/openkj/composer.json"

        # Link the document root to the expected path. Tugboat uses /docroot
        # by default. So, if Drupal is located at any other path in your git
        # repository, change that here. This example links /web to the docroot
        - ln -snf ~/test-drupal/web "${DOCROOT}"

      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      update:

        - composer install -d ~/test-drupal

        # Use the tugboat-specific Drupal settings
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.local.php" "${DOCROOT}/sites/default/"

        # Generate a unique hash_salt to secure the site
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> "${DOCROOT}/sites/default/settings.local.php"
        - echo "if (file_exists(\$app_root . '/' . \$site_path . '/settings.local.php')) { include \$app_root . '/' . \$site_path . '/settings.local.php'; }" >>"${DOCROOT}/sites/default/settings.php"

      # Commands that build the site. This is where you would add things
      # like feature reverts or any other drush commands required to
      # set up or configure the site. When a preview is built from a
      # base preview, the build workflow starts here, skipping the init
      # and update steps, because the results of those are inherited
      # from the base preview.
      build:
        - drush -r "${DOCROOT}" si
        - drush -r "${DOCROOT}" en openkj -y

  # What to call the service hosting MySQL. This name also acts as the
  # hostname to access the service by from the php service.
  mysql:

    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mysql:5
